worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream ingest {
        server ingest:8001;
    }

    upstream api {
        server api:8002;
    }

    server {
        listen 80;
        server_name _;

        location /v1/ingest {
            proxy_pass         http://ingest;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_read_timeout 10s;
        }

        location /api/ {
            proxy_pass         http://api;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location / {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    }
}
